{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "%load_ext autoreload\n",
    "%autoreload 2"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Requirement\n",
    "* The dataset can be downloaded from [this Kaggle competition](https://www.kaggle.com/c/ieee-fraud-detection).\n",
    "* In addition to the [Anaconda](https://www.anaconda.com) libraries, you need to install `category_encoders`, `selenium`, `geckodriver` and `scikit-learn` version 0.24 or higher.\n",
    "* You also need to set up an AWS account and install `awscli` and `sagemaker-python-sdk`."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "\n",
       "    <div class=\"bk-root\">\n",
       "        <a href=\"https://bokeh.org\" target=\"_blank\" class=\"bk-logo bk-logo-small bk-logo-notebook\"></a>\n",
       "        <span id=\"1001\">Loading BokehJS ...</span>\n",
       "    </div>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "application/javascript": [
       "\n",
       "(function(root) {\n",
       "  function now() {\n",
       "    return new Date();\n",
       "  }\n",
       "\n",
       "  var force = true;\n",
       "\n",
       "  if (typeof root._bokeh_onload_callbacks === \"undefined\" || force === true) {\n",
       "    root._bokeh_onload_callbacks = [];\n",
       "    root._bokeh_is_loading = undefined;\n",
       "  }\n",
       "\n",
       "  var JS_MIME_TYPE = 'application/javascript';\n",
       "  var HTML_MIME_TYPE = 'text/html';\n",
       "  var EXEC_MIME_TYPE = 'application/vnd.bokehjs_exec.v0+json';\n",
       "  var CLASS_NAME = 'output_bokeh rendered_html';\n",
       "\n",
       "  /**\n",
       "   * Render data to the DOM node\n",
       "   */\n",
       "  function render(props, node) {\n",
       "    var script = document.createElement(\"script\");\n",
       "    node.appendChild(script);\n",
       "  }\n",
       "\n",
       "  /**\n",
       "   * Handle when an output is cleared or removed\n",
       "   */\n",
       "  function handleClearOutput(event, handle) {\n",
       "    var cell = handle.cell;\n",
       "\n",
       "    var id = cell.output_area._bokeh_element_id;\n",
       "    var server_id = cell.output_area._bokeh_server_id;\n",
       "    // Clean up Bokeh references\n",
       "    if (id != null && id in Bokeh.index) {\n",
       "      Bokeh.index[id].model.document.clear();\n",
       "      delete Bokeh.index[id];\n",
       "    }\n",
       "\n",
       "    if (server_id !== undefined) {\n",
       "      // Clean up Bokeh references\n",
       "      var cmd = \"from bokeh.io.state import curstate; print(curstate().uuid_to_server['\" + server_id + \"'].get_sessions()[0].document.roots[0]._id)\";\n",
       "      cell.notebook.kernel.execute(cmd, {\n",
       "        iopub: {\n",
       "          output: function(msg) {\n",
       "            var id = msg.content.text.trim();\n",
       "            if (id in Bokeh.index) {\n",
       "              Bokeh.index[id].model.document.clear();\n",
       "              delete Bokeh.index[id];\n",
       "            }\n",
       "          }\n",
       "        }\n",
       "      });\n",
       "      // Destroy server and session\n",
       "      var cmd = \"import bokeh.io.notebook as ion; ion.destroy_server('\" + server_id + \"')\";\n",
       "      cell.notebook.kernel.execute(cmd);\n",
       "    }\n",
       "  }\n",
       "\n",
       "  /**\n",
       "   * Handle when a new output is added\n",
       "   */\n",
       "  function handleAddOutput(event, handle) {\n",
       "    var output_area = handle.output_area;\n",
       "    var output = handle.output;\n",
       "\n",
       "    // limit handleAddOutput to display_data with EXEC_MIME_TYPE content only\n",
       "    if ((output.output_type != \"display_data\") || (!output.data.hasOwnProperty(EXEC_MIME_TYPE))) {\n",
       "      return\n",
       "    }\n",
       "\n",
       "    var toinsert = output_area.element.find(\".\" + CLASS_NAME.split(' ')[0]);\n",
       "\n",
       "    if (output.metadata[EXEC_MIME_TYPE][\"id\"] !== undefined) {\n",
       "      toinsert[toinsert.length - 1].firstChild.textContent = output.data[JS_MIME_TYPE];\n",
       "      // store reference to embed id on output_area\n",
       "      output_area._bokeh_element_id = output.metadata[EXEC_MIME_TYPE][\"id\"];\n",
       "    }\n",
       "    if (output.metadata[EXEC_MIME_TYPE][\"server_id\"] !== undefined) {\n",
       "      var bk_div = document.createElement(\"div\");\n",
       "      bk_div.innerHTML = output.data[HTML_MIME_TYPE];\n",
       "      var script_attrs = bk_div.children[0].attributes;\n",
       "      for (var i = 0; i < script_attrs.length; i++) {\n",
       "        toinsert[toinsert.length - 1].firstChild.setAttribute(script_attrs[i].name, script_attrs[i].value);\n",
       "        toinsert[toinsert.length - 1].firstChild.textContent = bk_div.children[0].textContent\n",
       "      }\n",
       "      // store reference to server id on output_area\n",
       "      output_area._bokeh_server_id = output.metadata[EXEC_MIME_TYPE][\"server_id\"];\n",
       "    }\n",
       "  }\n",
       "\n",
       "  function register_renderer(events, OutputArea) {\n",
       "\n",
       "    function append_mime(data, metadata, element) {\n",
       "      // create a DOM node to render to\n",
       "      var toinsert = this.create_output_subarea(\n",
       "        metadata,\n",
       "        CLASS_NAME,\n",
       "        EXEC_MIME_TYPE\n",
       "      );\n",
       "      this.keyboard_manager.register_events(toinsert);\n",
       "      // Render to node\n",
       "      var props = {data: data, metadata: metadata[EXEC_MIME_TYPE]};\n",
       "      render(props, toinsert[toinsert.length - 1]);\n",
       "      element.append(toinsert);\n",
       "      return toinsert\n",
       "    }\n",
       "\n",
       "    /* Handle when an output is cleared or removed */\n",
       "    events.on('clear_output.CodeCell', handleClearOutput);\n",
       "    events.on('delete.Cell', handleClearOutput);\n",
       "\n",
       "    /* Handle when a new output is added */\n",
       "    events.on('output_added.OutputArea', handleAddOutput);\n",
       "\n",
       "    /**\n",
       "     * Register the mime type and append_mime function with output_area\n",
       "     */\n",
       "    OutputArea.prototype.register_mime_type(EXEC_MIME_TYPE, append_mime, {\n",
       "      /* Is output safe? */\n",
       "      safe: true,\n",
       "      /* Index of renderer in `output_area.display_order` */\n",
       "      index: 0\n",
       "    });\n",
       "  }\n",
       "\n",
       "  // register the mime type if in Jupyter Notebook environment and previously unregistered\n",
       "  if (root.Jupyter !== undefined) {\n",
       "    var events = require('base/js/events');\n",
       "    var OutputArea = require('notebook/js/outputarea').OutputArea;\n",
       "\n",
       "    if (OutputArea.prototype.mime_types().indexOf(EXEC_MIME_TYPE) == -1) {\n",
       "      register_renderer(events, OutputArea);\n",
       "    }\n",
       "  }\n",
       "\n",
       "  \n",
       "  if (typeof (root._bokeh_timeout) === \"undefined\" || force === true) {\n",
       "    root._bokeh_timeout = Date.now() + 5000;\n",
       "    root._bokeh_failed_load = false;\n",
       "  }\n",
       "\n",
       "  var NB_LOAD_WARNING = {'data': {'text/html':\n",
       "     \"<div style='background-color: #fdd'>\\n\"+\n",
       "     \"<p>\\n\"+\n",
       "     \"BokehJS does not appear to have successfully loaded. If loading BokehJS from CDN, this \\n\"+\n",
       "     \"may be due to a slow or bad network connection. Possible fixes:\\n\"+\n",
       "     \"</p>\\n\"+\n",
       "     \"<ul>\\n\"+\n",
       "     \"<li>re-rerun `output_notebook()` to attempt to load from CDN again, or</li>\\n\"+\n",
       "     \"<li>use INLINE resources instead, as so:</li>\\n\"+\n",
       "     \"</ul>\\n\"+\n",
       "     \"<code>\\n\"+\n",
       "     \"from bokeh.resources import INLINE\\n\"+\n",
       "     \"output_notebook(resources=INLINE)\\n\"+\n",
       "     \"</code>\\n\"+\n",
       "     \"</div>\"}};\n",
       "\n",
       "  function display_loaded() {\n",
       "    var el = document.getElementById(\"1001\");\n",
       "    if (el != null) {\n",
       "      el.textContent = \"BokehJS is loading...\";\n",
       "    }\n",
       "    if (root.Bokeh !== undefined) {\n",
       "      if (el != null) {\n",
       "        el.textContent = \"BokehJS \" + root.Bokeh.version + \" successfully loaded.\";\n",
       "      }\n",
       "    } else if (Date.now() < root._bokeh_timeout) {\n",
       "      setTimeout(display_loaded, 100)\n",
       "    }\n",
       "  }\n",
       "\n",
       "\n",
       "  function run_callbacks() {\n",
       "    try {\n",
       "      root._bokeh_onload_callbacks.forEach(function(callback) {\n",
       "        if (callback != null)\n",
       "          callback();\n",
       "      });\n",
       "    } finally {\n",
       "      delete root._bokeh_onload_callbacks\n",
       "    }\n",
       "    console.debug(\"Bokeh: all callbacks have finished\");\n",
       "  }\n",
       "\n",
       "  function load_libs(css_urls, js_urls, callback) {\n",
       "    if (css_urls == null) css_urls = [];\n",
       "    if (js_urls == null) js_urls = [];\n",
       "\n",
       "    root._bokeh_onload_callbacks.push(callback);\n",
       "    if (root._bokeh_is_loading > 0) {\n",
       "      console.debug(\"Bokeh: BokehJS is being loaded, scheduling callback at\", now());\n",
       "      return null;\n",
       "    }\n",
       "    if (js_urls == null || js_urls.length === 0) {\n",
       "      run_callbacks();\n",
       "      return null;\n",
       "    }\n",
       "    console.debug(\"Bokeh: BokehJS not loaded, scheduling load and callback at\", now());\n",
       "    root._bokeh_is_loading = css_urls.length + js_urls.length;\n",
       "\n",
       "    function on_load() {\n",
       "      root._bokeh_is_loading--;\n",
       "      if (root._bokeh_is_loading === 0) {\n",
       "        console.debug(\"Bokeh: all BokehJS libraries/stylesheets loaded\");\n",
       "        run_callbacks()\n",
       "      }\n",
       "    }\n",
       "\n",
       "    function on_error() {\n",
       "      console.error(\"failed to load \" + url);\n",
       "    }\n",
       "\n",
       "    for (var i = 0; i < css_urls.length; i++) {\n",
       "      var url = css_urls[i];\n",
       "      const element = document.createElement(\"link\");\n",
       "      element.onload = on_load;\n",
       "      element.onerror = on_error;\n",
       "      element.rel = \"stylesheet\";\n",
       "      element.type = \"text/css\";\n",
       "      element.href = url;\n",
       "      console.debug(\"Bokeh: injecting link tag for BokehJS stylesheet: \", url);\n",
       "      document.body.appendChild(element);\n",
       "    }\n",
       "\n",
       "    const hashes = {\"https://cdn.bokeh.org/bokeh/release/bokeh-2.2.3.min.js\": \"T2yuo9Oe71Cz/I4X9Ac5+gpEa5a8PpJCDlqKYO0CfAuEszu1JrXLl8YugMqYe3sM\", \"https://cdn.bokeh.org/bokeh/release/bokeh-widgets-2.2.3.min.js\": \"98GDGJ0kOMCUMUePhksaQ/GYgB3+NH9h996V88sh3aOiUNX3N+fLXAtry6xctSZ6\", \"https://cdn.bokeh.org/bokeh/release/bokeh-tables-2.2.3.min.js\": \"89bArO+nlbP3sgakeHjCo1JYxYR5wufVgA3IbUvDY+K7w4zyxJqssu7wVnfeKCq8\"};\n",
       "\n",
       "    for (var i = 0; i < js_urls.length; i++) {\n",
       "      var url = js_urls[i];\n",
       "      var element = document.createElement('script');\n",
       "      element.onload = on_load;\n",
       "      element.onerror = on_error;\n",
       "      element.async = false;\n",
       "      element.src = url;\n",
       "      if (url in hashes) {\n",
       "        element.crossOrigin = \"anonymous\";\n",
       "        element.integrity = \"sha384-\" + hashes[url];\n",
       "      }\n",
       "      console.debug(\"Bokeh: injecting script tag for BokehJS library: \", url);\n",
       "      document.head.appendChild(element);\n",
       "    }\n",
       "  };\n",
       "\n",
       "  function inject_raw_css(css) {\n",
       "    const element = document.createElement(\"style\");\n",
       "    element.appendChild(document.createTextNode(css));\n",
       "    document.body.appendChild(element);\n",
       "  }\n",
       "\n",
       "  \n",
       "  var js_urls = [\"https://cdn.bokeh.org/bokeh/release/bokeh-2.2.3.min.js\", \"https://cdn.bokeh.org/bokeh/release/bokeh-widgets-2.2.3.min.js\", \"https://cdn.bokeh.org/bokeh/release/bokeh-tables-2.2.3.min.js\"];\n",
       "  var css_urls = [];\n",
       "  \n",
       "\n",
       "  var inline_js = [\n",
       "    function(Bokeh) {\n",
       "      Bokeh.set_log_level(\"info\");\n",
       "    },\n",
       "    function(Bokeh) {\n",
       "    \n",
       "    \n",
       "    }\n",
       "  ];\n",
       "\n",
       "  function run_inline_js() {\n",
       "    \n",
       "    if (root.Bokeh !== undefined || force === true) {\n",
       "      \n",
       "    for (var i = 0; i < inline_js.length; i++) {\n",
       "      inline_js[i].call(root, root.Bokeh);\n",
       "    }\n",
       "    if (force === true) {\n",
       "        display_loaded();\n",
       "      }} else if (Date.now() < root._bokeh_timeout) {\n",
       "      setTimeout(run_inline_js, 100);\n",
       "    } else if (!root._bokeh_failed_load) {\n",
       "      console.log(\"Bokeh: BokehJS failed to load within specified timeout.\");\n",
       "      root._bokeh_failed_load = true;\n",
       "    } else if (force !== true) {\n",
       "      var cell = $(document.getElementById(\"1001\")).parents('.cell').data().cell;\n",
       "      cell.output_area.append_execute_result(NB_LOAD_WARNING)\n",
       "    }\n",
       "\n",
       "  }\n",
       "\n",
       "  if (root._bokeh_is_loading === 0) {\n",
       "    console.debug(\"Bokeh: BokehJS loaded, going straight to plotting\");\n",
       "    run_inline_js();\n",
       "  } else {\n",
       "    load_libs(css_urls, js_urls, function() {\n",
       "      console.debug(\"Bokeh: BokehJS plotting callback run at\", now());\n",
       "      run_inline_js();\n",
       "    });\n",
       "  }\n",
       "}(window));"
      ],
      "application/vnd.bokehjs_load.v0+json": "\n(function(root) {\n  function now() {\n    return new Date();\n  }\n\n  var force = true;\n\n  if (typeof root._bokeh_onload_callbacks === \"undefined\" || force === true) {\n    root._bokeh_onload_callbacks = [];\n    root._bokeh_is_loading = undefined;\n  }\n\n  \n\n  \n  if (typeof (root._bokeh_timeout) === \"undefined\" || force === true) {\n    root._bokeh_timeout = Date.now() + 5000;\n    root._bokeh_failed_load = false;\n  }\n\n  var NB_LOAD_WARNING = {'data': {'text/html':\n     \"<div style='background-color: #fdd'>\\n\"+\n     \"<p>\\n\"+\n     \"BokehJS does not appear to have successfully loaded. If loading BokehJS from CDN, this \\n\"+\n     \"may be due to a slow or bad network connection. Possible fixes:\\n\"+\n     \"</p>\\n\"+\n     \"<ul>\\n\"+\n     \"<li>re-rerun `output_notebook()` to attempt to load from CDN again, or</li>\\n\"+\n     \"<li>use INLINE resources instead, as so:</li>\\n\"+\n     \"</ul>\\n\"+\n     \"<code>\\n\"+\n     \"from bokeh.resources import INLINE\\n\"+\n     \"output_notebook(resources=INLINE)\\n\"+\n     \"</code>\\n\"+\n     \"</div>\"}};\n\n  function display_loaded() {\n    var el = document.getElementById(\"1001\");\n    if (el != null) {\n      el.textContent = \"BokehJS is loading...\";\n    }\n    if (root.Bokeh !== undefined) {\n      if (el != null) {\n        el.textContent = \"BokehJS \" + root.Bokeh.version + \" successfully loaded.\";\n      }\n    } else if (Date.now() < root._bokeh_timeout) {\n      setTimeout(display_loaded, 100)\n    }\n  }\n\n\n  function run_callbacks() {\n    try {\n      root._bokeh_onload_callbacks.forEach(function(callback) {\n        if (callback != null)\n          callback();\n      });\n    } finally {\n      delete root._bokeh_onload_callbacks\n    }\n    console.debug(\"Bokeh: all callbacks have finished\");\n  }\n\n  function load_libs(css_urls, js_urls, callback) {\n    if (css_urls == null) css_urls = [];\n    if (js_urls == null) js_urls = [];\n\n    root._bokeh_onload_callbacks.push(callback);\n    if (root._bokeh_is_loading > 0) {\n      console.debug(\"Bokeh: BokehJS is being loaded, scheduling callback at\", now());\n      return null;\n    }\n    if (js_urls == null || js_urls.length === 0) {\n      run_callbacks();\n      return null;\n    }\n    console.debug(\"Bokeh: BokehJS not loaded, scheduling load and callback at\", now());\n    root._bokeh_is_loading = css_urls.length + js_urls.length;\n\n    function on_load() {\n      root._bokeh_is_loading--;\n      if (root._bokeh_is_loading === 0) {\n        console.debug(\"Bokeh: all BokehJS libraries/stylesheets loaded\");\n        run_callbacks()\n      }\n    }\n\n    function on_error() {\n      console.error(\"failed to load \" + url);\n    }\n\n    for (var i = 0; i < css_urls.length; i++) {\n      var url = css_urls[i];\n      const element = document.createElement(\"link\");\n      element.onload = on_load;\n      element.onerror = on_error;\n      element.rel = \"stylesheet\";\n      element.type = \"text/css\";\n      element.href = url;\n      console.debug(\"Bokeh: injecting link tag for BokehJS stylesheet: \", url);\n      document.body.appendChild(element);\n    }\n\n    const hashes = {\"https://cdn.bokeh.org/bokeh/release/bokeh-2.2.3.min.js\": \"T2yuo9Oe71Cz/I4X9Ac5+gpEa5a8PpJCDlqKYO0CfAuEszu1JrXLl8YugMqYe3sM\", \"https://cdn.bokeh.org/bokeh/release/bokeh-widgets-2.2.3.min.js\": \"98GDGJ0kOMCUMUePhksaQ/GYgB3+NH9h996V88sh3aOiUNX3N+fLXAtry6xctSZ6\", \"https://cdn.bokeh.org/bokeh/release/bokeh-tables-2.2.3.min.js\": \"89bArO+nlbP3sgakeHjCo1JYxYR5wufVgA3IbUvDY+K7w4zyxJqssu7wVnfeKCq8\"};\n\n    for (var i = 0; i < js_urls.length; i++) {\n      var url = js_urls[i];\n      var element = document.createElement('script');\n      element.onload = on_load;\n      element.onerror = on_error;\n      element.async = false;\n      element.src = url;\n      if (url in hashes) {\n        element.crossOrigin = \"anonymous\";\n        element.integrity = \"sha384-\" + hashes[url];\n      }\n      console.debug(\"Bokeh: injecting script tag for BokehJS library: \", url);\n      document.head.appendChild(element);\n    }\n  };\n\n  function inject_raw_css(css) {\n    const element = document.createElement(\"style\");\n    element.appendChild(document.createTextNode(css));\n    document.body.appendChild(element);\n  }\n\n  \n  var js_urls = [\"https://cdn.bokeh.org/bokeh/release/bokeh-2.2.3.min.js\", \"https://cdn.bokeh.org/bokeh/release/bokeh-widgets-2.2.3.min.js\", \"https://cdn.bokeh.org/bokeh/release/bokeh-tables-2.2.3.min.js\"];\n  var css_urls = [];\n  \n\n  var inline_js = [\n    function(Bokeh) {\n      Bokeh.set_log_level(\"info\");\n    },\n    function(Bokeh) {\n    \n    \n    }\n  ];\n\n  function run_inline_js() {\n    \n    if (root.Bokeh !== undefined || force === true) {\n      \n    for (var i = 0; i < inline_js.length; i++) {\n      inline_js[i].call(root, root.Bokeh);\n    }\n    if (force === true) {\n        display_loaded();\n      }} else if (Date.now() < root._bokeh_timeout) {\n      setTimeout(run_inline_js, 100);\n    } else if (!root._bokeh_failed_load) {\n      console.log(\"Bokeh: BokehJS failed to load within specified timeout.\");\n      root._bokeh_failed_load = true;\n    } else if (force !== true) {\n      var cell = $(document.getElementById(\"1001\")).parents('.cell').data().cell;\n      cell.output_area.append_execute_result(NB_LOAD_WARNING)\n    }\n\n  }\n\n  if (root._bokeh_is_loading === 0) {\n    console.debug(\"Bokeh: BokehJS loaded, going straight to plotting\");\n    run_inline_js();\n  } else {\n    load_libs(css_urls, js_urls, function() {\n      console.debug(\"Bokeh: BokehJS plotting callback run at\", now());\n      run_inline_js();\n    });\n  }\n}(window));"
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "import bokeh\n",
    "import os\n",
    "import warnings\n",
    "import boto3\n",
    "import sagemaker\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "from bokeh.io import export_png, export_svgs\n",
    "from bokeh.layouts import gridplot\n",
    "from bokeh.models import Band, ColumnDataSource, HoverTool, NumeralTickFormatter\n",
    "from bokeh.plotting import figure, show\n",
    "from sklearn.compose import make_column_transformer\n",
    "from sklearn.impute import SimpleImputer\n",
    "from sklearn.metrics import (accuracy_score, f1_score, precision_score, recall_score, \n",
    "                             average_precision_score, precision_recall_curve, roc_auc_score, roc_curve)\n",
    "from sklearn.model_selection import train_test_split\n",
    "from sklearn.pipeline import make_pipeline\n",
    "from sklearn.preprocessing import OrdinalEncoder\n",
    "from category_encoders import TargetEncoder\n",
    "from sagemaker.estimator import Estimator\n",
    "from sagemaker.inputs import TrainingInput\n",
    "from sagemaker.tuner import CategoricalParameter, ContinuousParameter, IntegerParameter, HyperparameterTuner\n",
    "warnings.filterwarnings(action='ignore')\n",
    "bokeh.io.output_notebook()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "def get_pred(score, thr=0.5):\n",
    "    return np.where(score >= thr, 1, 0)\n",
    "\n",
    "\n",
    "def is_number(x):\n",
    "    try:\n",
    "        float(x)\n",
    "        return 1\n",
    "    except:\n",
    "        return 0 \n",
    "\n",
    "\n",
    "def make_dirs(path):\n",
    "    if not os.path.exists(path):\n",
    "        os.makedirs(path)\n",
    "    \n",
    "\n",
    "def str_to_int(x):\n",
    "    return x if pd.isnull(x) else str(int(x))"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "#### Data Loading from Local Directory\n",
    "The Kaggle dataset was saved in the local directory `~/Data/ieee-fraud-detection` in advance."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "RAW_DATA_PATH = '../../Data/ieee-fraud-detection'"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "train_identity = pd.read_csv(os.path.join(RAW_DATA_PATH, 'train_identity.csv'))\n",
    "train_transaction = pd.read_csv(os.path.join(RAW_DATA_PATH, 'train_transaction.csv'))\n",
    "df_train = pd.merge(train_transaction, train_identity, on='TransactionID', how='left')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "cat_features = pd.Index(\n",
    "    ['ProductCD', 'addr1', 'addr2', 'P_emaildomain', 'R_emaildomain', 'DeviceType', 'DeviceInfo'] + [\n",
    "        f'card{i}' for i in range(1, 7)] + [f'M{i}' for i in range(1, 10)] + [f'id_{i}' for i in range(12, 39)])\n",
    "num_features = df_train.columns.difference(pd.Index(['TransactionID', 'TransactionDT', 'isFraud']) | cat_features)\n",
    "all_features = cat_features | num_features\n",
    "\n",
    "int_cat_features =  df_train[cat_features].select_dtypes('number').columns\n",
    "df_train[int_cat_features] = df_train[int_cat_features].applymap(str_to_int)\n",
    "df_train[cat_features] = df_train[cat_features].astype('str')"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Data Splitting and Preprocessing"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "df_X_train, df_X_test, df_y_train, df_y_test = train_test_split(\n",
    "    df_train[all_features], df_train['isFraud'], test_size=0.1, random_state=42, stratify=df_train['isFraud'])\n",
    "\n",
    "df_X_train, df_X_valid, df_y_train, df_y_valid = train_test_split(\n",
    "    df_X_train, df_y_train, test_size=0.15, random_state=42, stratify=df_y_train)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "cat_pipeline = make_pipeline(SimpleImputer(strategy='constant', fill_value='<unknown>'), \n",
    "                             OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1), \n",
    "                             TargetEncoder(min_samples_leaf=1, smoothing=1.0))\n",
    "num_pipeline = SimpleImputer(strategy='median')\n",
    "processor = make_column_transformer((cat_pipeline, cat_features), (num_pipeline, num_features))\n",
    "\n",
    "X_train = processor.fit_transform(df_X_train, df_y_train)\n",
    "X_valid = processor.transform(df_X_valid)\n",
    "X_test = processor.transform(df_X_test)\n",
    "\n",
    "dtrain = np.concatenate((df_y_train.values.reshape(-1, 1), X_train), axis=1)\n",
    "dvalid = np.concatenate((df_y_valid.values.reshape(-1, 1), X_valid), axis=1)\n",
    "dtest = X_test"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "prc_data_path = './prc_data'\n",
    "dir_names = ['train', 'valid', 'test']\n",
    "file_names = ['dtrain', 'dvalid', 'dtest']\n",
    "\n",
    "for dir_name in dir_names:\n",
    "    make_dirs(os.path.join(prc_data_path, dir_name))\n",
    "\n",
    "for dir_name, file_name, dataset in zip(dir_names, file_names, [dtrain, dvalid, dtest]):\n",
    "    np.savetxt(os.path.join(prc_data_path, dir_name, file_name) + '.csv', dataset, delimiter=',', fmt='%i')"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Hyperparameter Tuning\n",
    "#### Uploading Datasets to S3 Bucket"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "sagemaker_session = sagemaker.session.Session()\n",
    "BUCKET = sagemaker_session.default_bucket()\n",
    "BASE_JOB_PREFIX = 'ieee-fraud-detection'\n",
    "\n",
    "region = boto3.Session().region_name\n",
    "role = sagemaker.get_execution_role()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "%%time\n",
    "s3_client = boto3.client('s3')\n",
    "\n",
    "for dir_name, file_name in zip(dir_names, file_names):\n",
    "    s3_client.upload_file(\n",
    "        os.path.join(prc_data_path, dir_name, file_name) + '.csv', BUCKET, BASE_JOB_PREFIX + '/' + dir_name + '/' + file_name + '.csv')"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Defining Built-in Algorithm XGBoost Estimator"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "image_uri = sagemaker.image_uris.retrieve(\n",
    "    framework='xgboost',\n",
    "    region=region,\n",
    "    version='1.2-1',\n",
    "    py_version='py3',\n",
    "    instance_type='ml.m5.2xlarge'\n",
    ")\n",
    "model_output_uri = f's3://{BUCKET}/{BASE_JOB_PREFIX}/models'\n",
    "\n",
    "estimator = Estimator(\n",
    "    image_uri=image_uri,\n",
    "    role=role,\n",
    "    instance_count=1,\n",
    "    instance_type='ml.m5.2xlarge',\n",
    "    output_path=model_output_uri,\n",
    "    use_spot_instances=False,\n",
    "    max_wait=None\n",
    ")\n",
    "\n",
    "scale_pos_weight = float(df_y_train.shape[0] / df_y_train.sum() - 1.0)\n",
    "params = {\n",
    "    'booster': 'gbtree',\n",
    "    'verbosity': 0\n",
    "    'objective': 'binary:logistic',\n",
    "    'scale_pos_weight': scale_pos_weight,\n",
    "    'seed': 42,\n",
    "    'eval_metric': 'auc',\n",
    "    'num_round': 1000,\n",
    "    'early_stopping_rounds': 10\n",
    "}\n",
    "estimator.set_hyperparameters(**params)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Defining and Fitting HyperparameterTuner"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[autoreload of numpy.core.overrides failed: Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 783, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/numpy/core/overrides.py\", line 37, in <module>\n",
      "    add_docstring(\n",
      "RuntimeError: implement_array_function method already has a different docstring\n",
      "]\n",
      "[autoreload of numpy.core.multiarray failed: Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 783, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/numpy/core/multiarray.py\", line 76, in <module>\n",
      "    def empty_like(prototype, dtype=None, order=None, subok=None, shape=None):\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/numpy/core/overrides.py\", line 207, in decorator\n",
      "    'implement_array_function': implement_array_function,\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/numpy/core/overrides.py\", line 171, in decorator\n",
      "    functions defined in C, which otherwise don't have docstrings.\n",
      "RuntimeError: empty_like method already has a different docstring\n",
      "]\n",
      "[autoreload of numpy.matrixlib failed: Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 783, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/numpy/matrixlib/__init__.py\", line 6, in <module>\n",
      "    __all__ = defmatrix.__all__\n",
      "NameError: name 'defmatrix' is not defined\n",
      "]\n",
      "[autoreload of numpy.lib failed: Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 783, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/numpy/lib/__init__.py\", line 44, in <module>\n",
      "    __all__ += type_check.__all__\n",
      "NameError: name 'type_check' is not defined\n",
      "]\n",
      "[autoreload of numpy.ma.core failed: Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 292, in update_class\n",
      "    if (old_obj == new_obj) is True:\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/numpy/ma/core.py\", line 4113, in __eq__\n",
      "    return self._comparison(other, operator.eq)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/numpy/ma/core.py\", line 4051, in _comparison\n",
      "    mask = mask_or(smask, omask, copy=True)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/numpy/ma/core.py\", line 1753, in mask_or\n",
      "    return make_mask(umath.logical_or(m1, m2), copy=copy, shrink=shrink)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/numpy/ma/core.py\", line 1635, in make_mask\n",
      "    result = _shrink_mask(result)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/numpy/ma/core.py\", line 1544, in _shrink_mask\n",
      "    if m.dtype.names is None and not m.any():\n",
      "TypeError: _any() missing 1 required keyword-only argument: 'where'\n",
      "]\n",
      "[autoreload of numpy failed: Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 783, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/numpy/__init__.py\", line 369, in <module>\n",
      "    _mac_os_check()\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/numpy/__init__.py\", line 360, in _mac_os_check\n",
      "    x = linspace(0, 2, 5)\n",
      "  File \"<__array_function__ internals>\", line 5, in linspace\n",
      "TypeError: an integer is required (got type _NoValueType)\n",
      "]\n",
      "[autoreload of scipy.sparse.csgraph failed: Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 783, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/scipy/sparse/csgraph/__init__.py\", line 193, in <module>\n",
      "    from ._matching import (\n",
      "ImportError: cannot import name 'min_weight_full_bipartite_matching' from 'scipy.sparse.csgraph._matching' (/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/scipy/sparse/csgraph/_matching.cpython-38-darwin.so)\n",
      "]\n",
      "[autoreload of scipy.spatial.kdtree failed: Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 302, in update_class\n",
      "    if update_generic(old_obj, new_obj): continue\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 266, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: __init__() requires a code object with 0 free vars, not 1\n",
      "]\n",
      "[autoreload of scipy.spatial.distance failed: Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 266, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: _validate_wminkowski_kwargs() requires a code object with 0 free vars, not 3\n",
      "]\n",
      "[autoreload of scipy.sparse.linalg.isolve.iterative failed: Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 783, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/scipy/sparse/linalg/isolve/iterative.py\", line 150, in <module>\n",
      "    def bicg(A, b, x0=None, tol=1e-5, maxiter=None, M=None, callback=None, atol=None):\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/scipy/_lib/_threadsafety.py\", line 57, in decorator\n",
      "    return lock.decorate(func)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/scipy/_lib/_threadsafety.py\", line 45, in decorate\n",
      "    return scipy._lib.decorator.decorate(func, caller)\n",
      "AttributeError: module 'scipy' has no attribute '_lib'\n",
      "]\n",
      "[autoreload of numpy.testing._private.utils failed: Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 783, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/numpy/testing/_private/utils.py\", line 52, in <module>\n",
      "    HAS_LAPACK64 = numpy.linalg.lapack_lite._ilp64\n",
      "AttributeError: module 'numpy.linalg' has no attribute 'lapack_lite'\n",
      "]\n",
      "[autoreload of numpy.testing failed: Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 783, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/numpy/testing/__init__.py\", line 16, in <module>\n",
      "    __all__ = _private.utils.__all__ + ['TestCase', 'run_module_suite']\n",
      "NameError: name '_private' is not defined\n",
      "]\n",
      "[autoreload of scipy.stats._continuous_distns failed: Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 783, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/scipy/stats/_continuous_distns.py\", line 113, in <module>\n",
      "    ksone = ksone_gen(a=0.0, b=1.0, name='ksone')\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/scipy/stats/_distn_infrastructure.py\", line 1657, in __init__\n",
      "    super(rv_continuous, self).__init__(seed)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/scipy/stats/_distn_infrastructure.py\", line 613, in __init__\n",
      "    self._random_state = check_random_state(seed)\n",
      "AttributeError: module 'numpy.random' has no attribute 'mtrand'\n",
      "]\n",
      "[autoreload of scipy.stats._discrete_distns failed: Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 783, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/scipy/stats/_discrete_distns.py\", line 96, in <module>\n",
      "    binom = binom_gen(name='binom')\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/scipy/stats/_distn_infrastructure.py\", line 2920, in __init__\n",
      "    super(rv_discrete, self).__init__(seed)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/scipy/stats/_distn_infrastructure.py\", line 613, in __init__\n",
      "    self._random_state = check_random_state(seed)\n",
      "AttributeError: module 'numpy.random' has no attribute 'mtrand'\n",
      "]\n",
      "[autoreload of scipy.stats._multivariate failed: Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 783, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/scipy/stats/_multivariate.py\", line 692, in <module>\n",
      "    multivariate_normal = multivariate_normal_gen()\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/scipy/stats/_multivariate.py\", line 357, in __init__\n",
      "    super(multivariate_normal_gen, self).__init__(seed)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/scipy/stats/_multivariate.py\", line 194, in __init__\n",
      "    self._random_state = check_random_state(seed)\n",
      "AttributeError: module 'numpy.random' has no attribute 'mtrand'\n",
      "]\n",
      "[autoreload of sklearn.utils.fixes failed: Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 783, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/sklearn/utils/fixes.py\", line 111, in <module>\n",
      "    class loguniform(scipy.stats.reciprocal):\n",
      "AttributeError: module 'scipy' has no attribute 'stats'\n",
      "]\n",
      "[autoreload of sklearn.utils.validation failed: Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 266, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: assert_all_finite() requires a code object with 4 free vars, not 5\n",
      "]\n",
      "[autoreload of sklearn.utils.class_weight failed: Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 266, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: compute_class_weight() requires a code object with 4 free vars, not 5\n",
      "]\n",
      "[autoreload of sklearn.utils failed: Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 266, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: safe_sqr() requires a code object with 4 free vars, not 5\n",
      "]\n",
      "[autoreload of sklearn.base failed: Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 266, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: clone() requires a code object with 4 free vars, not 5\n",
      "]\n",
      "[autoreload of sklearn.pipeline failed: Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 783, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/sklearn/pipeline.py\", line 30, in <module>\n",
      "    from .utils.fixes import delayed\n",
      "ImportError: cannot import name 'delayed' from 'sklearn.utils.fixes' (/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/sklearn/utils/fixes.py)\n",
      "]\n",
      "[autoreload of sklearn.preprocessing._function_transformer failed: Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 302, in update_class\n",
      "    if update_generic(old_obj, new_obj): continue\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 266, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: __init__() requires a code object with 4 free vars, not 5\n",
      "]\n",
      "[autoreload of sklearn.utils.extmath failed: Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 266, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: safe_sparse_dot() requires a code object with 4 free vars, not 5\n",
      "]\n",
      "[autoreload of sklearn.utils.sparsefuncs failed: Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 266, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: incr_mean_variance_axis() requires a code object with 4 free vars, not 5\n",
      "]\n",
      "[autoreload of sklearn.preprocessing._label failed: Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 302, in update_class\n",
      "    if update_generic(old_obj, new_obj): continue\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 266, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: __init__() requires a code object with 4 free vars, not 5\n",
      "]\n",
      "[autoreload of sklearn.preprocessing._encoders failed: Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 302, in update_class\n",
      "    if update_generic(old_obj, new_obj): continue\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 266, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: __init__() requires a code object with 4 free vars, not 5\n",
      "]\n",
      "[autoreload of sklearn.preprocessing._data failed: Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 266, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: scale() requires a code object with 4 free vars, not 5\n",
      "]\n",
      "[autoreload of sklearn.preprocessing._discretization failed: Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 302, in update_class\n",
      "    if update_generic(old_obj, new_obj): continue\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 266, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: __init__() requires a code object with 4 free vars, not 5\n",
      "]\n",
      "[autoreload of sklearn.compose._column_transformer failed: Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 783, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/sklearn/compose/_column_transformer.py\", line 26, in <module>\n",
      "    from ..utils.fixes import delayed\n",
      "ImportError: cannot import name 'delayed' from 'sklearn.utils.fixes' (/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/sklearn/utils/fixes.py)\n",
      "]\n",
      "[autoreload of sklearn.compose._target failed: Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 302, in update_class\n",
      "    if update_generic(old_obj, new_obj): continue\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 266, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: __init__() requires a code object with 4 free vars, not 5\n",
      "]\n",
      "[autoreload of sklearn.impute._base failed: Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 302, in update_class\n",
      "    if update_generic(old_obj, new_obj): continue\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 266, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: __init__() requires a code object with 4 free vars, not 5\n",
      "]\n",
      "[autoreload of sklearn.metrics._ranking failed: Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 266, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: average_precision_score() requires a code object with 4 free vars, not 5\n",
      "]\n",
      "[autoreload of sklearn.metrics._classification failed: Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 266, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: accuracy_score() requires a code object with 4 free vars, not 5\n",
      "]\n",
      "[autoreload of sklearn.metrics.cluster._supervised failed: Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 266, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: contingency_matrix() requires a code object with 4 free vars, not 5\n",
      "]\n",
      "[autoreload of sklearn.metrics.pairwise failed: Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 783, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 32, in <module>\n",
      "    from ..utils.fixes import delayed\n",
      "ImportError: cannot import name 'delayed' from 'sklearn.utils.fixes' (/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/sklearn/utils/fixes.py)\n",
      "]\n",
      "[autoreload of sklearn.metrics.cluster._unsupervised failed: Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 266, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: silhouette_score() requires a code object with 4 free vars, not 5\n",
      "]\n",
      "[autoreload of sklearn.metrics.cluster._bicluster failed: Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 266, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: consensus_score() requires a code object with 4 free vars, not 5\n",
      "]\n",
      "[autoreload of sklearn.metrics._regression failed: Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 783, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/sklearn/metrics/_regression.py\", line 35, in <module>\n",
      "    from ..utils.stats import _weighted_percentile\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/sklearn/utils/stats.py\", line 4, in <module>\n",
      "    from .fixes import _take_along_axis\n",
      "ImportError: cannot import name '_take_along_axis' from 'sklearn.utils.fixes' (/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/sklearn/utils/fixes.py)\n",
      "]\n",
      "[autoreload of sklearn.metrics._scorer failed: Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 783, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/sklearn/metrics/_scorer.py\", line 27, in <module>\n",
      "    from . import (r2_score, median_absolute_error, max_error, mean_absolute_error,\n",
      "ImportError: cannot import name 'top_k_accuracy_score' from 'sklearn.metrics' (/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/sklearn/metrics/__init__.py)\n",
      "]\n",
      "[autoreload of sklearn.metrics._plot.roc_curve failed: Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 302, in update_class\n",
      "    if update_generic(old_obj, new_obj): continue\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 266, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: __init__() requires a code object with 0 free vars, not 5\n",
      "]\n",
      "[autoreload of sklearn.metrics._plot.precision_recall_curve failed: Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 302, in update_class\n",
      "    if update_generic(old_obj, new_obj): continue\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 266, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: __init__() requires a code object with 0 free vars, not 5\n",
      "]\n",
      "[autoreload of sklearn.metrics._plot.confusion_matrix failed: Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 302, in update_class\n",
      "    if update_generic(old_obj, new_obj): continue\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 266, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: __init__() requires a code object with 0 free vars, not 5\n",
      "]\n",
      "[autoreload of sklearn.metrics failed: Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 783, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/sklearn/metrics/__init__.py\", line 71, in <module>\n",
      "    from ._regression import mean_absolute_percentage_error\n",
      "ImportError: cannot import name 'mean_absolute_percentage_error' from 'sklearn.metrics._regression' (/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/sklearn/metrics/_regression.py)\n",
      "]\n",
      "[autoreload of sklearn.neighbors._base failed: Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 783, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 35, in <module>\n",
      "    from ..utils.fixes import delayed\n",
      "ImportError: cannot import name 'delayed' from 'sklearn.utils.fixes' (/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/sklearn/utils/fixes.py)\n",
      "]\n",
      "[autoreload of sklearn.neighbors._unsupervised failed: Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 302, in update_class\n",
      "    if update_generic(old_obj, new_obj): continue\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 266, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: __init__() requires a code object with 4 free vars, not 5\n",
      "]\n",
      "[autoreload of sklearn.neighbors._graph failed: Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 266, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: kneighbors_graph() requires a code object with 4 free vars, not 5\n",
      "]\n",
      "[autoreload of sklearn.neighbors._classification failed: Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 302, in update_class\n",
      "    if update_generic(old_obj, new_obj): continue\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 266, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: __init__() requires a code object with 4 free vars, not 5\n",
      "]\n",
      "[autoreload of sklearn.neighbors._regression failed: Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 302, in update_class\n",
      "    if update_generic(old_obj, new_obj): continue\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 266, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: __init__() requires a code object with 4 free vars, not 5\n",
      "]\n",
      "[autoreload of sklearn.neighbors._nearest_centroid failed: Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 302, in update_class\n",
      "    if update_generic(old_obj, new_obj): continue\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 266, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: __init__() requires a code object with 4 free vars, not 5\n",
      "]\n",
      "[autoreload of sklearn.neighbors._kde failed: Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 302, in update_class\n",
      "    if update_generic(old_obj, new_obj): continue\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 266, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: __init__() requires a code object with 4 free vars, not 5\n",
      "]\n",
      "[autoreload of sklearn.neighbors._lof failed: Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 302, in update_class\n",
      "    if update_generic(old_obj, new_obj): continue\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 266, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: __init__() requires a code object with 4 free vars, not 5\n",
      "]\n",
      "[autoreload of sklearn.linear_model._base failed: Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 783, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/sklearn/linear_model/_base.py\", line 40, in <module>\n",
      "    from ..utils.fixes import delayed\n",
      "ImportError: cannot import name 'delayed' from 'sklearn.utils.fixes' (/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/sklearn/utils/fixes.py)\n",
      "]\n",
      "[autoreload of sklearn.linear_model._bayes failed: Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 302, in update_class\n",
      "    if update_generic(old_obj, new_obj): continue\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 266, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: __init__() requires a code object with 4 free vars, not 5\n",
      "]\n",
      "[autoreload of sklearn.model_selection._split failed: Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 302, in update_class\n",
      "    if update_generic(old_obj, new_obj): continue\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 266, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: __init__() requires a code object with 4 free vars, not 5\n",
      "]\n",
      "[autoreload of sklearn.model_selection._validation failed: Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 783, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 28, in <module>\n",
      "    from ..utils.fixes import delayed\n",
      "ImportError: cannot import name 'delayed' from 'sklearn.utils.fixes' (/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/sklearn/utils/fixes.py)\n",
      "]\n",
      "[autoreload of sklearn.model_selection._search failed: Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 783, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/sklearn/model_selection/_search.py\", line 32, in <module>\n",
      "    from ._validation import _insert_error_scores\n",
      "ImportError: cannot import name '_insert_error_scores' from 'sklearn.model_selection._validation' (/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/sklearn/model_selection/_validation.py)\n",
      "]\n",
      "[autoreload of sklearn.linear_model._least_angle failed: Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 783, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/sklearn/linear_model/_least_angle.py\", line 28, in <module>\n",
      "    from ..utils.fixes import delayed\n",
      "ImportError: cannot import name 'delayed' from 'sklearn.utils.fixes' (/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/sklearn/utils/fixes.py)\n",
      "]\n",
      "[autoreload of sklearn.linear_model._coordinate_descent failed: Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 783, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py\", line 28, in <module>\n",
      "    from ..utils.fixes import delayed\n",
      "ImportError: cannot import name 'delayed' from 'sklearn.utils.fixes' (/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/sklearn/utils/fixes.py)\n",
      "]\n",
      "[autoreload of sklearn.linear_model._huber failed: Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 302, in update_class\n",
      "    if update_generic(old_obj, new_obj): continue\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 266, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: __init__() requires a code object with 4 free vars, not 5\n",
      "]\n",
      "[autoreload of sklearn.linear_model._stochastic_gradient failed: Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 783, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/sklearn/linear_model/_stochastic_gradient.py\", line 23, in <module>\n",
      "    from ..utils.fixes import delayed\n",
      "ImportError: cannot import name 'delayed' from 'sklearn.utils.fixes' (/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/sklearn/utils/fixes.py)\n",
      "]\n",
      "[autoreload of sklearn.linear_model._sag failed: Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 266, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: sag_solver() requires a code object with 4 free vars, not 5\n",
      "]\n",
      "[autoreload of sklearn.linear_model._ridge failed: Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 783, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/sklearn/linear_model/_ridge.py\", line 987, in <module>\n",
      "    class _X_CenterStackOp(sparse.linalg.LinearOperator):\n",
      "AttributeError: module 'scipy.sparse' has no attribute 'linalg'\n",
      "]\n",
      "[autoreload of sklearn.svm._base failed: Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 302, in update_class\n",
      "    if update_generic(old_obj, new_obj): continue\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 323, in update_property\n",
      "    update_generic(old.fget, new.fget)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 266, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: _pairwise() requires a code object with 0 free vars, not 2\n",
      "]\n",
      "[autoreload of sklearn.svm._classes failed: Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 302, in update_class\n",
      "    if update_generic(old_obj, new_obj): continue\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 266, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: __init__() requires a code object with 4 free vars, not 5\n",
      "]\n",
      "[autoreload of sklearn.svm._bounds failed: Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 266, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: l1_min_c() requires a code object with 4 free vars, not 5\n",
      "]\n",
      "[autoreload of sklearn.linear_model._logistic failed: Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 783, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py\", line 35, in <module>\n",
      "    from ..utils.fixes import delayed\n",
      "ImportError: cannot import name 'delayed' from 'sklearn.utils.fixes' (/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/sklearn/utils/fixes.py)\n",
      "]\n",
      "[autoreload of sklearn.linear_model._omp failed: Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 783, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/sklearn/linear_model/_omp.py\", line 20, in <module>\n",
      "    from ..utils.fixes import delayed\n",
      "ImportError: cannot import name 'delayed' from 'sklearn.utils.fixes' (/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/sklearn/utils/fixes.py)\n",
      "]\n",
      "[autoreload of sklearn.linear_model._passive_aggressive failed: Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 302, in update_class\n",
      "    if update_generic(old_obj, new_obj): continue\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 266, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: __init__() requires a code object with 4 free vars, not 5\n",
      "]\n",
      "[autoreload of sklearn.linear_model._perceptron failed: Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 302, in update_class\n",
      "    if update_generic(old_obj, new_obj): continue\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 266, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: __init__() requires a code object with 4 free vars, not 5\n",
      "]\n",
      "[autoreload of sklearn.linear_model._ransac failed: Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 302, in update_class\n",
      "    if update_generic(old_obj, new_obj): continue\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 266, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: __init__() requires a code object with 4 free vars, not 5\n",
      "]\n",
      "[autoreload of sklearn.linear_model._theil_sen failed: Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 783, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/sklearn/linear_model/_theil_sen.py\", line 24, in <module>\n",
      "    from ..utils.fixes import delayed\n",
      "ImportError: cannot import name 'delayed' from 'sklearn.utils.fixes' (/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/sklearn/utils/fixes.py)\n",
      "]\n",
      "[autoreload of sklearn.decomposition._dict_learning failed: Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 783, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/sklearn/decomposition/_dict_learning.py\", line 22, in <module>\n",
      "    from ..utils.fixes import delayed\n",
      "ImportError: cannot import name 'delayed' from 'sklearn.utils.fixes' (/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/sklearn/utils/fixes.py)\n",
      "]\n",
      "[autoreload of sklearn.decomposition._nmf failed: Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 266, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: non_negative_factorization() requires a code object with 4 free vars, not 5\n",
      "]\n",
      "[autoreload of sklearn.decomposition._pca failed: Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 302, in update_class\n",
      "    if update_generic(old_obj, new_obj): continue\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 266, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: __init__() requires a code object with 4 free vars, not 5\n",
      "]\n",
      "[autoreload of sklearn.decomposition._incremental_pca failed: Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 302, in update_class\n",
      "    if update_generic(old_obj, new_obj): continue\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 266, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: __init__() requires a code object with 4 free vars, not 5\n",
      "]\n",
      "[autoreload of sklearn.decomposition._kernel_pca failed: Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 302, in update_class\n",
      "    if update_generic(old_obj, new_obj): continue\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 266, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: __init__() requires a code object with 4 free vars, not 5\n",
      "]\n",
      "[autoreload of sklearn.decomposition._sparse_pca failed: Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 302, in update_class\n",
      "    if update_generic(old_obj, new_obj): continue\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 266, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: __init__() requires a code object with 4 free vars, not 5\n",
      "]\n",
      "[autoreload of sklearn.decomposition._truncated_svd failed: Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 302, in update_class\n",
      "    if update_generic(old_obj, new_obj): continue\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 266, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: __init__() requires a code object with 4 free vars, not 5\n",
      "]\n",
      "[autoreload of sklearn.decomposition._fastica failed: Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 266, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: fastica() requires a code object with 4 free vars, not 5\n",
      "]\n",
      "[autoreload of sklearn.decomposition._factor_analysis failed: Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 302, in update_class\n",
      "    if update_generic(old_obj, new_obj): continue\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 266, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: __init__() requires a code object with 4 free vars, not 5\n",
      "]\n",
      "[autoreload of sklearn.decomposition._lda failed: Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 783, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/sklearn/decomposition/_lda.py\", line 24, in <module>\n",
      "    from ..utils.fixes import delayed\n",
      "ImportError: cannot import name 'delayed' from 'sklearn.utils.fixes' (/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/sklearn/utils/fixes.py)\n",
      "]\n",
      "[autoreload of sklearn.neighbors._nca failed: Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 302, in update_class\n",
      "    if update_generic(old_obj, new_obj): continue\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 266, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: __init__() requires a code object with 4 free vars, not 5\n",
      "]\n",
      "[autoreload of sklearn.impute._knn failed: Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 302, in update_class\n",
      "    if update_generic(old_obj, new_obj): continue\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 266, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: __init__() requires a code object with 4 free vars, not 5\n",
      "]\n",
      "[autoreload of numpy.ma.mrecords failed: Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 783, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/opt/anaconda3/envs/sagemaker-pipelines/lib/python3.8/site-packages/numpy/ma/mrecords.py\", line 26, in <module>\n",
      "    _byteorderconv = np.core.records._byteorderconv\n",
      "AttributeError: module 'numpy.core' has no attribute 'records'\n",
      "]\n"
     ]
    },
    {
     "ename": "TypeError",
     "evalue": "__init__() got an unexpected keyword argument 'scailing_type'",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mTypeError\u001b[0m                                 Traceback (most recent call last)",
      "\u001b[0;32m<ipython-input-4-c6b7e1039678>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[1;32m      1\u001b[0m hyperparameter_ranges = {\n\u001b[0;32m----> 2\u001b[0;31m     \u001b[0;34m'max_depth'\u001b[0m\u001b[0;34m:\u001b[0m \u001b[0mIntegerParameter\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;36m1\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;36m30\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mscailing_type\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;34m'Auto'\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m      3\u001b[0m     \u001b[0;34m'eta'\u001b[0m\u001b[0;34m:\u001b[0m \u001b[0mContinuousParameter\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;36m0.01\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;36m1.0\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mscailing_type\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;34m'Auto'\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      4\u001b[0m     \u001b[0;34m'gamma'\u001b[0m\u001b[0;34m:\u001b[0m \u001b[0mContinuousParameter\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;36m0.0\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;36m1.0\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mscailing_type\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;34m'Auto'\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      5\u001b[0m     \u001b[0;34m'min_child_weight'\u001b[0m\u001b[0;34m:\u001b[0m \u001b[0mContinuousParameter\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;36m1e-06\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;36m1.0\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mscailing_type\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;34m'Auto'\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mTypeError\u001b[0m: __init__() got an unexpected keyword argument 'scailing_type'"
     ]
    }
   ],
   "source": [
    "hyperparameter_ranges = {\n",
    "    'max_depth': IntegerParameter(1, 30, scailing_type='Auto'),\n",
    "    'eta': ContinuousParameter(0.01, 1.0, scailing_type='Auto'),\n",
    "    'gamma': ContinuousParameter(0.0, 1.0, scailing_type='Auto'),\n",
    "    'min_child_weight': ContinuousParameter(1e-06, 1.0, scailing_type='Auto'),\n",
    "    'subsample': ContinuousParameter(0.1, 1.0, scailing_type='Auto'),\n",
    "    'colsample_bytree': ContinuousParameter(0.1, 1.0, scailing_type='Auto')\n",
    "}\n",
    "\n",
    "tuner = HyperparameterTuner(\n",
    "    estimator,\n",
    "    'validation:auc',\n",
    "    hyperparameter_ranges,\n",
    "    objective_type='Maximize',\n",
    "    max_jobs=30,\n",
    "    max_parallel_jobs=3,\n",
    "    base_tuning_job_name=f'{BASE_JOB_PREFIX}-xgb-hpo',\n",
    "    early_stopping_type='Auto'\n",
    ")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "%%time\n",
    "train_input = TrainingInput(\n",
    "    s3_data=f's3://{BUCKET}/{BASE_JOB_PREFIX}/train/', \n",
    "    content_type='text/csv'\n",
    ")\n",
    "valid_input = TrainingInput(\n",
    "    s3_data=f's3://{BUCKET}/{BASE_JOB_PREFIX}/valid/', \n",
    "    content_type='text/csv'\n",
    ")\n",
    "\n",
    "tuner.fit(\n",
    "    {\n",
    "        'train': train_input, \n",
    "        'validation': valid_input\n",
    "    }\n",
    ")\n",
    "\n",
    "best_estimator = tuner.best_estimator()\n",
    "best_params = best_estimator.hyperparameters()\n",
    "tuning_job_name = tuner.latest_tuning_job.name"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Analyzing Hyperparameter Tuning Results"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "tuning_job_analytics = sagemaker.HyperparameterTuningJobAnalytics(tuning_job_name)\n",
    "df_viz = tuning_job_analytics.dataframe()\n",
    "\n",
    "image_path = './img'\n",
    "make_dirs(image_path)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "df_viz.sort_values('FinalObjectiveValue', ascending=False)[:10]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "class HoverHelper():\n",
    "    def __init__(self, tuning_job_analytics):\n",
    "        self.tuning_job_analytics = tuning_job_analytics\n",
    "\n",
    "    def hovertool(self):\n",
    "        tooltips = [\n",
    "            ('TrainingJobName', '@TrainingJobName'),\n",
    "            ('FinalObjectiveValue', '@FinalObjectiveValue')\n",
    "        ]\n",
    "    \n",
    "        for key in self.tuning_job_analytics.tuning_ranges.keys():\n",
    "            tooltips.append((key, '@{%s}' % key) )\n",
    "\n",
    "        hover_tool = HoverTool(tooltips=tooltips)\n",
    "        return hover_tool\n",
    "\n",
    "    def tools(self, standard_tools='pan, crosshair, wheel_zoom, zoom_in, zoom_out, undo, reset'):\n",
    "        return [self.hovertool(), standard_tools]\n",
    "    \n",
    "    \n",
    "def make_grid(figures, n_cols):\n",
    "    rows = []\n",
    "    for i, figure in enumerate(figures):\n",
    "        if i % n_cols == 0:\n",
    "            cols = []\n",
    "        elif (i % n_cols == n_cols - 1) or (i == len(figures) - 1):\n",
    "            rows.append(cols)\n",
    "        cols.append(figure)\n",
    "    return rows"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "hover_helper = HoverHelper(tuning_job_analytics)\n",
    "\n",
    "p = figure(plot_width=800, plot_height=400, tools=hover_helper.tools(), \n",
    "           title='Convergence Plot', x_axis_type='datetime', x_axis_label='Training Start Time', y_axis_label='AUROC')\n",
    "_ = p.line(source=df_viz, x='TrainingStartTime', y='FinalObjectiveValue', color='coral', line_width=1.5)\n",
    "_ = p.circle(source=df_viz, x='TrainingStartTime', y='FinalObjectiveValue', line_color='coral', line_width=1.5, fill_color='white')\n",
    "\n",
    "p.title.align = 'center'\n",
    "p.title.text_font_size = '11pt'\n",
    "p.xgrid.grid_line_color = None\n",
    "p.yaxis.formatter = NumeralTickFormatter(format='0.0%')\n",
    "\n",
    "show(p)\n",
    "\n",
    "p.output_backend = 'svg'\n",
    "_ = export_svgs(p, filename=f'{image_path}/convergence_plot.svg')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "df_viz = df_viz.reset_index()\n",
    "df_viz['index'] = (df_viz['index'] + df_viz['index'].min()) / (df_viz['index'].max() - df_viz['index'].min())\n",
    "\n",
    "figures = []\n",
    "for param_name, param_range in tuning_job_analytics.tuning_ranges.items():\n",
    "    categorical_args = dict()\n",
    "    if param_range.get('Values'):          \n",
    "        values = param_range['Values']\n",
    "        if sum([is_number(x) for x in values]) == len(values):\n",
    "            print('Hyperparameter %s is tuned as categorical, but all values are numeric.' % param_name)\n",
    "        else:\n",
    "            categorical_args['x_range'] = values\n",
    "\n",
    "    plot = figure(plot_width=400, plot_height=400, tools=hover_helper.tools(), \n",
    "                  x_axis_label=param_name, y_axis_label='AUROC', **categorical_args)\n",
    "    plot.circle(source=df_viz, x=param_name, y='FinalObjectiveValue', color='black', alpha='index')\n",
    "    plot.xgrid.grid_line_color = None\n",
    "    plot.yaxis.formatter = NumeralTickFormatter(format='0.0%')\n",
    "    figures.append(plot)\n",
    "\n",
    "p = gridplot(make_grid(figures, 3), toolbar_location='right')\n",
    "\n",
    "show(p)\n",
    "\n",
    "_ = export_png(p, filename=f'{image_path}/partial_dependence_plot.png')"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Model Evaluation\n",
    "## Defining Transformer and Prediction"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "%%time\n",
    "transformer = best_estimator.transformer(\n",
    "    instance_count=1, \n",
    "    instance_type='ml.m5.2xlarge', \n",
    "    output_path=f's3://{BUCKET}/{BASE_JOB_PREFIX}/pred'\n",
    ")\n",
    "\n",
    "_ = transformer.transform(\n",
    "    data=f's3://{BUCKET}/{BASE_JOB_PREFIX}/test/',\n",
    "    content_type='text/csv', \n",
    "    split_type='Line'\n",
    ")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "#### Downloading Prediction Scores to Local Directory"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "s3_client.download_file(BUCKET, f'{BASE_JOB_PREFIX}/pred/dtest.csv.out', os.path.join(prc_data_path, 'test', 'dtest.csv.out'))\n",
    "scores = pd.read_csv(os.path.join(prc_data_path, 'test', 'dtest.csv.out'), header=None).values"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Measuring Predictive Performance"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "preds = get_pred(scores)\n",
    "\n",
    "print('ACCURACY: {0:.2%}, PRECISION: {1:.2%}, RECALL: {2:.2%}, F1: {3:.2%}'.format(\n",
    "    accuracy_score(df_y_test, preds), precision_score(df_y_test, preds), recall_score(df_y_test, preds), f1_score(df_y_test, preds)))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "source = pd.DataFrame(roc_curve(df_y_test, scores), index=['fpr', 'tpr', 'thr']).T\n",
    "\n",
    "p = figure(plot_height=400, title='ROC Curve (AUROC {:.2%})'.format(roc_auc_score(df_y_test, scores)), \n",
    "           x_axis_label='False Positive Rate', y_axis_label='True Positive Rate')\n",
    "_ = p.line(source=source, x='fpr', y='tpr', color='coral', line_width=1.5)\n",
    "_ = p.line(source=source, x='fpr', y='fpr', color='black', line_dash='dashed')\n",
    "\n",
    "p.title.align = 'center'\n",
    "p.title.text_font_size = '11pt'\n",
    "p.xgrid.grid_line_color = None\n",
    "p.xaxis.formatter = NumeralTickFormatter(format='0.0%')\n",
    "p.yaxis.formatter = NumeralTickFormatter(format='0.0%')\n",
    "\n",
    "show(p)\n",
    "\n",
    "p.output_backend = 'svg'\n",
    "_ = export_svgs(p, filename=f'{image_path}/roc_curve.svg')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "source = pd.DataFrame(precision_recall_curve(df_y_test, scores), index=['recall', 'precision', 'thr']).T\n",
    "\n",
    "p = figure(plot_height=400, title='Precision - Recall Curve (AUPRC {:.2%})'.format(average_precision_score(df_y_test, scores)), \n",
    "           x_axis_label='Recall', y_axis_label='Precision')\n",
    "_ = p.line(source=source, x='recall', y='precision', color='coral', line_width=1.0)\n",
    "band = Band(source=ColumnDataSource(data=dict(recall=source['recall'], precision=source['precision'])), \n",
    "            base='recall', upper='precision', level='underlay', fill_color='coral', fill_alpha=0.2)\n",
    "p.add_layout(band)\n",
    "\n",
    "p.title.align = 'center'\n",
    "p.title.text_font_size = '11pt'\n",
    "p.xgrid.grid_line_color = None\n",
    "p.xaxis.formatter = NumeralTickFormatter(format='0.0%')\n",
    "p.yaxis.formatter = NumeralTickFormatter(format='0.0%')\n",
    "\n",
    "show(p)\n",
    "\n",
    "p.output_backend = 'svg'\n",
    "_ = export_svgs(p, filename=f'{image_path}/pr_curve.svg')"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Model Retraining\n",
    "### Data Loading, Splitting, Preprocessing and Uploading"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "test_identity = pd.read_csv(os.path.join(RAW_DATA_PATH, 'test_identity.csv')) \n",
    "test_transaction = pd.read_csv(os.path.join(RAW_DATA_PATH, 'test_transaction.csv'))\n",
    "df_test = pd.merge(test_transaction, test_identity, on='TransactionID', how='left')\n",
    "df_test = df_test.rename(columns={'id-{:02d}'.format(i): 'id_{:02d}'.format(i) for i in range(1, 39)})\n",
    "\n",
    "df_test[int_cat_features] = df_test[int_cat_features].applymap(str_to_int)\n",
    "df_test[cat_features] = df_test[cat_features].astype('str')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "df_X_retrain, df_X_revalid, df_y_retrain, df_y_revalid = train_test_split(\n",
    "    df_train[all_features], df_train['isFraud'], test_size=0.15, random_state=42, stratify=df_train['isFraud'])\n",
    "\n",
    "X_retrain = processor.fit_transform(df_X_retrain, df_y_retrain)\n",
    "X_revalid = processor.transform(df_X_revalid)\n",
    "X_retest = processor.transform(df_test[all_features])\n",
    "\n",
    "dtrain = np.concatenate((df_y_retrain.values.reshape(-1, 1), X_retrain), axis=1)\n",
    "dvalid = np.concatenate((df_y_revalid.values.reshape(-1, 1), X_revalid), axis=1)\n",
    "dtest = X_retest"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "dir_names = ['retrain', 'revalid', 'retest']\n",
    "\n",
    "for dir_name in dir_names:\n",
    "    make_dirs(os.path.join(prc_data_path, dir_name))\n",
    "\n",
    "for dir_name, file_name, dataset in zip(dir_names, file_names, [dtrain, dvalid, dtest]):\n",
    "    np.savetxt(os.path.join(prc_data_path, dir_name, file_name) + '.csv', dataset, delimiter=',', fmt='%i')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "%%time\n",
    "for dir_name, file_name in zip(dir_names, file_names):\n",
    "    s3_client.upload_file(\n",
    "        os.path.join(prc_data_path, dir_name, file_name) + '.csv', BUCKET, BASE_JOB_PREFIX + '/' + dir_name + '/' + file_name + '.csv')"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Defining and Fitting Estimator"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "full_estimator = Estimator(\n",
    "    image_uri=image_uri,\n",
    "    role=role,\n",
    "    instance_count=1,\n",
    "    instance_type='ml.m5.2xlarge',\n",
    "    output_path=model_output_uri,\n",
    "    use_spot_instances=False,\n",
    "    max_wait=None\n",
    ")\n",
    "\n",
    "best_params = best_estimator.hyperparameters()\n",
    "_ = best_params.pop('_tuning_objective_metric')\n",
    "params.update(best_params)\n",
    "full_estimator.set_hyperparameters(**params)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "%%time\n",
    "retrain_input = TrainingInput(\n",
    "    s3_data=f's3://{BUCKET}/{BASE_JOB_PREFIX}/retrain/', \n",
    "    content_type='text/csv'\n",
    ")\n",
    "revalid_input = TrainingInput(\n",
    "    s3_data=f's3://{BUCKET}/{BASE_JOB_PREFIX}/revalid/', \n",
    "    content_type='text/csv'\n",
    ")\n",
    "\n",
    "full_estimator.fit(\n",
    "    {\n",
    "    'train': retrain_input,\n",
    "    'validation': revalid_input\n",
    "    }\n",
    ")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Defining Transformer and Prediction"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "%%time\n",
    "full_transformer = full_estimator.transformer(\n",
    "    instance_count=1, \n",
    "    instance_type='ml.m5.2xlarge', \n",
    "    output_path=f's3://{BUCKET}/{BASE_JOB_PREFIX}/repred'\n",
    ")\n",
    "\n",
    "_ = full_transformer.transform(\n",
    "    data=f's3://{BUCKET}/{BASE_JOB_PREFIX}/retest/',\n",
    "    content_type='text/csv', \n",
    "    split_type='Line'\n",
    ")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "#### Downloading Prediction Scores to Local Directory"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "s3_client.download_file(BUCKET, f'{BASE_JOB_PREFIX}/repred/dtest.csv.out', os.path.join(prc_data_path, 'retest', 'dtest.csv.out'))\n",
    "scores = pd.read_csv(os.path.join(prc_data_path, 'retest', 'dtest.csv.out'), header=None).values"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "submission = pd.DataFrame({'TransactionID': df_test['TransactionID'].values, 'isFraud': scores.flatten()})\n",
    "submission.to_csv('./submission.csv', index=False)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
